### ISSUE TITLE
footer svg's not showing on chrome

### ISSUE THREAD

**Issue by nahid18** [fabe/site#16]
The footer svg files showing on Firefox but not on Chrome.

Footer on Firefox. Looks perfect.
![mozila footer](https://user-images.githubusercontent.com/43277262/65238720-209a2780-daff-11e9-84aa-f01e7ef1360b.png)

Footer on Chrome. 
![chrome footer](https://user-images.githubusercontent.com/43277262/65238782-458e9a80-daff-11e9-913b-8cedfec8bd32.png)

Kindly check this issue. Thanks.

**Comment by nahid18** [comment]
@fabe Can you kindly check this issue?

**Comment by fabe** [comment]
Hey @nahid18, thanks for opening this! Unfortunately I can't reproduce this issue, it might be only happening on Windows in a specific viewport, which is fine for me at the moment.

PS: I don't really update this site anymore (it's fairly old), so don't use it as a base for anything. Looking into some of the Gatsby [starters](https://www.gatsbyjs.org/starters/) or [themes](https://github.com/topics/gatsby-theme) might be better!
